export enum PointDistributionLogsEvent {
    Warning = "warning",
    Error = "error",
}

export enum PointDistributionLogsLevel {
    VAULT_NOT_FOUND = "VAULT_NOT_FOUND",
    NO_ACTIVE_CAMPAIGN = "NO_ACTIVE_CAMPAIGN",
    TOTAL_DEPOSIT_ZERO = "TOTAL_DEPOSIT_ZERO",
    DISTRIBUTE_USER_FAILED = "DISTRIBUTE_USER_FAILED",
    INDIRECT_POOL_NO_BALANCES = "INDIRECT_POOL_NO_BALANCES",
    INDIRECT_POOL_TOTAL_BALANCE_ZERO = "INDIRECT_POOL_TOTAL_BALANCE_ZERO",
    PROCESS_FAILED = "PROCESS_POINT_DISTRIBUTION_FAILED",
    NO_NEW_POINTS = "NO_NEW_POINTS",
}
